databases:
  - name: flowcraft-plumbing-db
    plan: free

services:
  - type: web
    name: flowcraft-plumbing
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/site-settings/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: flowcraft-plumbing-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
      - key: COMPANY_NOTIFICATION_EMAIL
        value: bookings@flowcraftplumbing.com
      - key: SEND_CUSTOMER_CONFIRMATION_EMAIL
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@flowcraftplumbing.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: CLOUDINARY_URL
        sync: false  
