# Generated by Django 5.2.17 on 2026-08-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_unit",
                    models.CharField(blank=True, default="/ visit", max_length=40),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of feature strings, e.g. ["Inspection", "Minor repair"]',
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("cta_text", models.CharField(default="Get Started", max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Package",
                "verbose_name_plural": "Service Packages",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "designation",
                    models.CharField(
                        default="Certified Plumbing Technician", max_length=150
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=200)),
                ("years_experience", models.PositiveIntegerField(default=5)),
                ("certifications", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="technicians/"),
                ),
                ("photo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Technician",
                "verbose_name_plural": "Technicians",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_name",
                    models.CharField(
                        default="Wrench", help_text="Lucide icon name.", max_length=60
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback external image URL if no upload.",
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        blank=True, default="starting from", max_length=40
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "service_name_text",
                    models.CharField(
                        blank=True,
                        help_text="Free-text service name if not tied to a Service record.",
                        max_length=150,
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("preferred_time", models.TimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("problem_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("staff_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
