# Generated by Django 5.2.17 on 2026-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("is_24_hours", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Business Hours",
                "verbose_name_plural": "Business Hours",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback external image URL if no upload.",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="company/videos/"
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=15)),
                ("jobs_completed", models.PositiveIntegerField(default=5000)),
                ("happy_customers", models.PositiveIntegerField(default=3500)),
                (
                    "support_availability",
                    models.CharField(default="24/7", max_length=50),
                ),
                ("service_areas_count", models.PositiveIntegerField(default=10)),
                ("certified_technicians", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "About / Company Info",
                "verbose_name_plural": "About / Company Info",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(default="+91 90000 00000", max_length=30)),
                ("emergency_phone", models.CharField(blank=True, max_length=30)),
                (
                    "email",
                    models.EmailField(
                        default="info@flowcraftplumbing.com", max_length=254
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+919000000000",
                        help_text="Include country code, digits only after '+', e.g. +919000000000",
                        max_length=30,
                    ),
                ),
                (
                    "whatsapp_default_message",
                    models.CharField(
                        default="Hi, I need plumbing service. Please share the available options and pricing.",
                        max_length=255,
                    ),
                ),
                ("address_line", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "emergency_availability_text",
                    models.CharField(
                        default="24/7 Emergency Service Available", max_length=120
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
            },
        ),
        migrations.CreateModel(
            name="EmergencyBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Plumbing Emergency? We're Ready to Help.",
                        max_length=255,
                    ),
                ),
                (
                    "subtext",
                    models.CharField(
                        blank=True,
                        default="24/7 emergency plumbing response across our service areas.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Emergency Banner",
                "verbose_name_plural": "Emergency Banner",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoogleMapSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embed_url",
                    models.TextField(
                        blank=True, help_text="Google Maps embed <iframe> src URL."
                    ),
                ),
                ("directions_url", models.URLField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Map Settings",
                "verbose_name_plural": "Google Map Settings",
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Reliable Plumbing. Done Right the First Time.",
                        max_length=255,
                    ),
                ),
                (
                    "subheading",
                    models.TextField(
                        default="Professional plumbing solutions for homes, offices and commercial properties — available when you need us."
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        default="Licensed & Insured Plumbers",
                        max_length=120,
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                ("background_image_url", models.URLField(blank=True)),
                (
                    "background_video",
                    models.FileField(blank=True, null=True, upload_to="hero/videos/"),
                ),
                (
                    "background_video_url",
                    models.URLField(
                        blank=True, help_text="External video URL fallback (mp4)."
                    ),
                ),
                (
                    "cta_primary_text",
                    models.CharField(default="Book a Plumber", max_length=60),
                ),
                (
                    "cta_secondary_text",
                    models.CharField(default="Call Now", max_length=60),
                ),
                ("show_emergency_badge", models.BooleanField(default=True)),
                ("show_fast_response_badge", models.BooleanField(default=True)),
                ("show_licensed_badge", models.BooleanField(default=True)),
                ("show_transparent_pricing_badge", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="HowItWorksStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("icon_name", models.CharField(default="Phone", max_length=60)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "How It Works Step",
                "verbose_name_plural": "How It Works Steps",
                "ordering": ["order", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="FlowCraft Plumbing | Reliable Plumbing Services",
                        max_length=255,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords.",
                        max_length=500,
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/"),
                ),
                ("favicon", models.ImageField(blank=True, null=True, upload_to="seo/")),
                (
                    "business_name",
                    models.CharField(default="FlowCraft Plumbing", max_length=120),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "SEO Setting",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_service_available", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Service Area",
                "verbose_name_plural": "Service Areas",
                "ordering": ["order", "city", "area"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="FlowCraft Plumbing", max_length=120),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                (
                    "footer_description",
                    models.TextField(
                        blank=True,
                        help_text="Short company description shown in the footer.",
                    ),
                ),
                ("is_maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter / X"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Media Link",
                "verbose_name_plural": "Social Media Links",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="ShieldCheck",
                        help_text="Lucide icon name, e.g. ShieldCheck, Clock, Wrench.",
                        max_length=60,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Why Choose Us Feature",
                "verbose_name_plural": "Why Choose Us Features",
                "ordering": ["order", "id"],
            },
        ),
    ]
